/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    GameBoard: (() => {
      const tableId = new TableId("", "GameBoard");
      return defineComponent(
        world,
        {
          piece: RecsType.Number,
          color: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Turn: (() => {
      const tableId = new TableId("", "Turn");
      return defineComponent(
        world,
        {
          turn: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    GameOver: (() => {
      const tableId = new TableId("", "GameOver");
      return defineComponent(
        world,
        {
          checkmate: RecsType.Boolean,
          stalemate: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
