// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameBoard, GameBoardData, GameBoardTableId } from "./tables/GameBoard.sol";
import { Turn, TurnTableId } from "./tables/Turn.sol";
