// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum Piece {
  Pawn,
  Knight,
  Bishop,
  Rook,
  Queen,
  King,
  Empty
}

enum Color {
  White,
  Black,
  Empty
}
