// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameSystem {
  function startGame() external;

  function movePiece(uint8 from, uint8 to) external;
}
