// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameSystem {
  function startGame() external;

  function getBoard() external view returns (bytes32[64] memory);
}
