// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IBishopSystem } from "./IBishopSystem.sol";
import { IGameSystem } from "./IGameSystem.sol";
import { IKingSystem } from "./IKingSystem.sol";
import { IKnightSystem } from "./IKnightSystem.sol";
import { IPawnSystem } from "./IPawnSystem.sol";
import { IQueenSystem } from "./IQueenSystem.sol";
import { IRookSystem } from "./IRookSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IBishopSystem,
  IGameSystem,
  IKingSystem,
  IKnightSystem,
  IPawnSystem,
  IQueenSystem,
  IRookSystem
{

}
